language: node_js
node_js:
  - node
  - 4.2
script: npm test
before_install:
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -y rethinkdb
  - rethinkdb --daemon
  - sudo pip install backports.ssl_match_hostname rethinkdb
  - rethinkdb import -d ./test/seeds/rethinkData/bkmrkd_stage
