os:
  - linux
language: node_js
node_js:
  - node
  - 6
script: npm test
before_script:
  - psql -c 'create database bkmrkd_test;' -U postgres
addons:
  postgresql: "9.5"
services:
  - postgresql
env:
  - DB_HOST=127.0.0.1
  - DB_NAME=bkmrkd_test
  - DB_PORT=5432
  - DB_USER=postgres
  - DB_PASS=
  - PORT=3000
