sudo: required

dist: trusty

language: node_js

node_js:
  - node
  - 6

env:
  global:
    - DB_MIGRATE=true
    - DB_HOST=localhost
    - DB_NAME=bkmrkd_test
    - DB_PORT=5432
    - DB_USER=postgres
    - DB_PASS= PORT=3000

addons:
  postgresql: "9.5"

script: npm test

before_install: yarn global add greenkeeper-lockfile@1

before_script:
  - psql -c 'create database bkmrkd_test;' -U postgres
  - cp .env.sample .env
  - npm run migrate:up
  - snyk auth $SNYK_TOKEN
  - greenkeeper-lockfile-update

after_script: greenkeeper-lockfile-upload

after_success:
  - bash <(curl -s https://codecov.io/bash)
