source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-flash'
gem 'sinatra-partial'
gem 'unicorn'
gem 'haml'
gem 'foreman'
gem 'redcarpet'
gem 'mongo'
gem 'bson_ext'
gem 'sass'
