export default {
  ADD_BOOKMARKS: 'ADD_BOOKMARKS',
  DESTROY_BOOKMARK: 'DESTROY_BOOKMARK',
  REQUEST_LOADING: 'REQUEST_LOADING',
  REQUEST_SUCCESS: 'REQUEST_SUCCESS',
  REQUEST_FAILURE: 'REQUEST_FAILURE'
}
